language: java

addons:
  sonarqube: true

env:
  global:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/caverna
    - SPRING_DATASOURCE_USERNAME=caverna
    - SPRING_DATASOURCE_PASSWORD=
    - NODE_ENV=development

services:
  - postgresql

before_script:
  - psql -c 'create database caverna;' -U postgres

script:
  - ./gradlew test
